[project]
name = "rag-search-engin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nltk==3.9.1",
    "numpy==2.3.3",
    "openai>=3.14.1",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
]

[tool.pyright]
include = ["cli"]
exclude = [".venv", "cache", "data"]
venvPath = "."
venv = ".venv"
diagnosticMode = "openFilesOnly"
useLibraryCodeForTypes = false
